name: unde_salesman
description: UNDE Salesman App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Пакет с флагами стран
  dash_flags: ^0.1.1
  # Пакет гибкой сетки
  flexible_grid_view: ^0.0.2
  # State management
  get: ^4.6.5
  # powerful HTTP client
  dio: ^5.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

 # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    

  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Ubuntu
    fonts:
      - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
        style: normal
        weight: 700
      - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
        style: normal
        weight: 500

  - family: Inter
    fonts:
      - asset: assets/fonts/Inter/static/Inter-Bold.ttf
        style: normal
        weight: 700
      - asset: assets/fonts/Inter/static/Inter-Medium.ttf
        style: normal
        weight: 500
      - asset: assets/fonts/Inter/static/Inter-Regular.ttf
        style: normal
        weight: 400