name: unde_salesman
description: UNDE Salesman App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  # Пакет с флагами стран
  dash_flags: ^0.1.1
  # Пакет  об устройстве
  device_info_plus: ^9.0.1
  # powerful HTTP client
  dio: ^5.1.2
   # Пакет для локализации
  easy_localization: ^3.0.2
  # Пакет гибкой сетки
  flexible_grid_view: ^0.0.2
  flutter:
    sdk: flutter
  # Пакет для работы с окружением
  flutter_dotenv: ^5.0.2
  # пакет по работе с svg иконками
  flutter_svg: ^2.0.6
  # State management
  get: ^4.6.5
  # Пакет  об устройстве
  package_info_plus: ^4.0.1
  # cache
  shared_preferences: ^2.1.1
  
  
  vfx_flutter_common:
    git:
      url: https://gitlab.com/frostyland/vfx_flutter_common.git
      ref: "torexo"



dev_dependencies:
  flutter_test:
    sdk: flutter
  # линтер
  very_good_analysis: ^4.0.0+1


flutter:

  uses-material-design: true

 # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/translations/
  
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Ubuntu
    fonts:
      - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
        style: normal
        weight: 700
      - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
        style: normal
        weight: 500

  - family: Inter
    fonts:
      - asset: assets/fonts/Inter/static/Inter-Bold.ttf
        style: normal
        weight: 700
      - asset: assets/fonts/Inter/static/Inter-Medium.ttf
        style: normal
        weight: 500
      - asset: assets/fonts/Inter/static/Inter-Regular.ttf
        style: normal
        weight: 400